/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Item extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "model_version" })
    modelVersion: string;

    @SpeakeasyMetadata()
    @Expose({ name: "run_id" })
    runId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "token" })
    token: string;
}
