/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class Testcase extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "full_prompt" })
    fullPrompt?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "ideal" })
    ideal?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "model_response" })
    modelResponse?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "retrieval_context" })
    retrievalContext?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "testset_id" })
    testsetId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "user_query" })
    userQuery: string;
}
