/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { z } from "zod";

export type Security = {
    apiKeyHeader?: string | undefined;
};

/** @internal */
export namespace Security$ {
    export type Inbound = {
        APIKeyHeader?: string | undefined;
    };

    export const inboundSchema: z.ZodType<Security, z.ZodTypeDef, Inbound> = z
        .object({
            APIKeyHeader: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.APIKeyHeader === undefined ? null : { apiKeyHeader: v.APIKeyHeader }),
            };
        });

    export type Outbound = {
        APIKeyHeader?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Security> = z
        .object({
            apiKeyHeader: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.apiKeyHeader === undefined ? null : { APIKeyHeader: v.apiKeyHeader }),
            };
        });
}
